package com.etlsolutions.examples.weather.data;

import java.util.Objects;

/**
 * The RequestToken class is a wrapper class which wraps the token to access the
 * web site. This is usually generated by the web site for each user.
 *
 * @author zc
 */
public final class RequestToken {

    private final String value;

    public RequestToken(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public int hashCode() {

        int hash = 67;
        hash = 29 * hash + Objects.hashCode(this.value);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {

        if (obj == null) {
            return false;
        }

        if (getClass() != obj.getClass()) {
            return false;
        }

        final RequestToken other = (RequestToken) obj;
        return Objects.equals(this.value, other.value);
    }

    @Override
    public String toString() {
        return "RequestToken{value=" + value + '}';
    }
}
